# Generated by Django 5.2.12 on 2026-09-29 01:09

import django.utils.timezone
from django.db import migrations, models


def populate_historical_item_prices(apps, schema_editor):
    ItensCompra = apps.get_model('core', 'ItensCompra')
    items = ItensCompra.objects.select_related('livro').iterator()
    batch = []
    for item in items:
        item.preco = item.livro.preco
        batch.append(item)
        if len(batch) == 500:
            ItensCompra.objects.bulk_update(batch, ['preco'])
            batch = []
    if batch:
        ItensCompra.objects.bulk_update(batch, ['preco'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_compra_itenscompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_pagamento',
            field=models.IntegerField(choices=[(1, 'Cartão de Crédito'), (2, 'Cartão de Débito'), (3, 'PIX'), (4, 'Boleto'), (5, 'Transferência Bancária'), (6, 'Dinheiro'), (7, 'Outro'), (8, 'Cheque')], default=1),
        ),
        migrations.AddField(
            model_name='itenscompra',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.RunPython(populate_historical_item_prices, migrations.RunPython.noop),
    ]
